### ISSUE TITLE
Auto-merge is stuck

### ISSUE THREAD

**Issue by lucacome** [dependabot/fetch-metadata#52] opened 2021-07-06 18:03 UTC
I'm using this action to enable auto-merge for Dependabot. Everything seemed to work fine, but the PR is not being merged. I'm not sure how to debug this and probably it doesn't have anything to do with the action but I don't know where else to report it 😬 

![image](https://user-images.githubusercontent.com/603885/124646486-8dec8900-de49-11eb-952a-b1b38206b1e4.png)

It's been attempting to auto-merge for more than 24 hours now.

This is the PR https://github.com/nginxinc/nginx-asg-sync/pull/108
and this the action https://github.com/nginxinc/nginx-asg-sync/blob/master/.github/workflows/dependabot-auto-merge.yml

Does anybody know how to fix this?

Thanks.

**Comment by asciimike** [comment] 2021-07-09 16:46
Odd, it seems like something is wonky with the PR automerge feature. I can reach out to that team and see if they have any thoughts!

**Comment by lucacome** [comment] 2021-07-10 00:55
Thank you so much @asciimike . Yes, that would be great any additional insight you can get I'd appreciate.

**Comment by lucacome** [comment] 2021-07-14 17:33
@asciimike it seems like Dependabot can't merge to a protected branch, I tried removing the protection and it started merging the PRs. Is there something I can do about this? When I try to add Dependabot to the list of apps allowed to push to master, it doesn't show up.

Separately the PRs merged by Dependabot are not being closed https://github.com/nginxinc/nginx-asg-sync/pull/108

**Comment by asciimike** [comment] 2021-07-14 18:18
> Is there something I can do about this? When I try to add Dependabot to the list of apps allowed to push to master, it doesn't show up.

This just came up in the context of codeowners, so I'll see if I can work with that team to see what we can do about allowing Dependabot to push to restricted branches

> Separately the PRs merged by Dependabot are not being closed nginxinc/nginx-asg-sync#108 is this the expected behavior?

Unfortunately this is a known issue with the UI displaying the right state :(

I've been chatting with the team on how to prioritize getting that fixed.

**Comment by JacobEvelyn** [comment] 2021-07-14 19:27
For what it's worth I reached out to GitHub Support about this issue about a month ago. Here's what they said:

> The default authentication tokens used by GitHub Actions belongs to user github-actions[bot]. It seems that you've enabled the "Restrict who can push to matching branches" rule. The default GitHub Actions actor does not have the permission to push (merge or commit) to the protected branch.
> 
> You may need to make a few changes in your Actions workflow file. First, you will need to create a personal access token (PAT) for user with either admin permissions or a user with write access who's been granted push permission to the protected branch of the repository (Step 12 in this help doc article):
> 
> https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
> 
> You can change this default value by setting the environmental variable GITHUB_TOKEN to the access token that you created in the previous step.
> 
> You'll need to create a repository secret giving it a name e.g "GITHUB_TOKEN" with the actual token as its value. See here how to create secrets and use them in a GitHub Actions workflow file:
> 
> https://docs.github.com/en/actions/reference/encrypted-secrets

Though I would have rather granted `github-actions[bot]` write access to our repo, they said that was not possible. I followed their advice instead and it's been working for us, though I'd love a simpler solution.

**Comment by asciimike** [comment] 2021-07-14 19:35
> Though I would have rather granted github-actions[bot] write access to our repo, they said that was not possible.

Agreed, the PAT solution is pretty ugly :(

**Comment by asciimike** [comment] 2021-07-14 20:38
As a side note, I re-discovered https://github.com/dependabot/feedback/issues/86, and am talking to the folks who own branch protection rules about how we can get Dependabot added.

**Comment by lucacome** [comment] 2021-08-09 22:13
@asciimike any updates on this?

**Comment by asciimike** [comment] 2021-08-09 23:36
At this point it looks like the problem is more of "we should show an error rather than hang forever", as I think adding Dependabot as a trusted actor is going to be a bit more work.

**Comment by lucacome** [comment] 2021-08-10 19:15
https://github.com/dependabot/dependabot-core/issues/2480

**Comment by brrygrdn** [comment] 2022-03-22 16:56
👋🏻 @lucacome I'm going to close this out as we are tracking this in core since it is a problem with the service vs protected branches.

Unfortunately I don't have anything to share on this right now.

**Closed by brrygrdn** 2022-03-22 16:56 UTC
Labels: bug

**Comment by lucacome** [comment] 2022-03-22 17:06
Thanks for the update @brrygrdn !
